development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:df08ceb590439154417fb353b40d440a@barb.redistogo.com:9148/
  channel_prefix: HereToLearn_production
